FROM php:8.2-apache

RUN docker-php-ext-install pdo pdo_mysql

# Copia TUDO pro Apache
COPY public/ /var/www/html/
COPY db.php /var/www/html/

# Garante permissões
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

EXPOSE 80
